version: "2.1"
services:
  docker-powerdns-recurs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    image: docker-powerdns-recurs
    container_name: docker-powerdns-recurs
    ports:
      - "53:53"
      - "53:53/udp"
    networks:
      - default
    command: --local-port=53
networks:
  default:

